version: "3.3"
services:
  postgis:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgis
    ports:
      - 5432:5432
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
    restart: always
    networks:
      - webgis
    environment:
      - POSTGRES_USER=change_username
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=change_db_name
volumes:
  pgdata:
networks:
  webgis:
    external: true